version: "2.1"
services:
  mongo:
    image: mongo:3.2.4
    ports:
    - 27017:27017
    command: --smallfiles
        
  glarimy-cities-profile:
    image: glarimy-cities-profile:latest
    ports:
    - 8080:8080
    links:
    - mongo